config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'

devise_scope :customer do
  get '/customers/sign_up', to: 'customers/registrations#new'
  post '/customers', to: 'customers/registrations#create'

  get '/customers/sign_in', to: 'customers/sessions#new'
  post '/customers/sign_in', to: 'customers/sessions#create'
  delete '/customers/sign_out', to: 'customers/sessions#destroy'
end


devise_for :customers, skip: [:registrations, :sessions, :passwords]

devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

scope module: :public do

get 'home/about' => 'homes#about'

resources :items, only: [:index, :show]
#get '/items' => 'items#index'
#get '/items/:id' => 'items#show'

#get '/customers/edit' => 'customers#edit'
#patch '/customers' => 'customers#update'
#get '/customers' => 'customers#show'
get '/customers/unsubscribe' => 'customers#unsubscribe'
patch '/customers/withdraw' => 'customers#withdraw'
resource :customers, only: [:show, :edit, :update]

delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
resources :cart_items, except: [:show, :edit, :new]

get '/orders/confirm' => 'orders#confirm'
get '/orders/complete' => 'orders#complete'
resources :orders
#post '/orders' => 'orders#create'
#get '/orders' => 'orders#index'
#get '/orders/:id' => 'orders#show'
#get '/orders/new' => 'orders#new'

#get '/addresses' => 'addresses#index'
#get '/addresses/:id/edit' => 'addresses#edit'
#post '/addresses' =>'addresses#create'
#patch '/addresses/:id' => 'addresses#update'
#delete '/addresses/:id' => 'addresses#destroy'

resources :addresses

end




 namespace :admin do
  resources :customers
  resources :genres
  resources :items
  resources :orders
  resources :order_items
 end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  	if @customer.update(customer_params)
  		redirect_to admin_customer_path(@customer)
  	else
  		render "edit"
  	end
  end

  private

  def customer_params
  	params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :postal_code,:address, :phone_number, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  before_action :reject_user, only: [:create]
  protected

  def reject_user
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to customers_sign_up_path
      end
    end

  end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
 <%= form_with model:@customer, url: admin_customer_path(@customer), local:true do |f| %>


 <div class="form-group row">
    <%= f.label :id,"会員ID" , class:"col-sm-2 col-form-label" %>
      <%= f.text_field :id, class:"form-control col-sm-3" %>
  </div>

  <div class="form-group row">
    <%= f.label :name,"氏名" , class:"col-sm-2 col-form-label" %>
    <%= f.text_field :last_name, class:"form-control col-sm-3" %>
    <%= f.text_field :first_name, class:"form-control col-sm-3 ml-3" %>
  </div>

  <div class="form-group row">
    <%= f.label :name,"フリガナ" , class:"col-sm-2 col-form-label" %>
    <%= f.text_field :last_name_kana, class:"form-control col-sm-3" %>
    <%= f.text_field :first_name_kana, class:"form-control col-sm-3 ml-3" %>
  </div>

  <div class="form-group row">
    <%= f.label :postal_code,"郵便番号" , class:"col-sm-2 col-form-label" %>
      <%= f.text_field :postal_code, class:"form-control col-sm-3" %>
  </div>

  <div class="form-group row">
    <%= f.label :address, "住所", class: "col-sm-2 col-form-label" %>
    <%= f.text_field :address, class: "form-control col-sm-6" %>
  </div>


  <div class="form-group row">
    <%= f.label :telephone_number, "電話番号", class: "col-sm-2 col-form-label" %>
    <%= f.text_field :telephone_number, class: "form-control col-sm-3" %>
  </div>

  <div class="form-group row">
    <%= f.label  "メールアドレス", class: "col-sm-2 col-form-label" %>
    <%= f.text_field :email, class: "form-control col-sm-3" %>
  </div>

  <div class="form-group row">
    <%= f.label "有効ステータス", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.label :is_active, '有効' %>
      <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active, '退会' %>
      <%= f.radio_button :is_active, :false %>
    </div>
  </div>


  <div><%= f.submit "変更を保存する", class:"btn btn-primary" %></div>
  <% end %>

app/views/admin/customers/index.html.erb
<h2>会員一覧</h2>

<dic class ="row col-sm-8 offset-sm-2">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer) %></td>
          <!-- <%#= link_to admin_customer_path(customer) do %><%#=customer.last_name %><%#=customer.first_name %><%# end %></td> -->
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_active %>
            <span class="green">有効</span>
          <% else %>
            <span class="secondary">退会</span>
          <% end %>
        </td>
        <!-- <td><%#= customer.is_active ? "有効" : "退会" %></td> -->
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>

<div class="row">
 <div class="col-sm-6 offset-sm-2">

  <div class="form-group row">
   <div class="col-sm-3">会員ID</div>
    <div><%= @customer.id %></div>
  </div>

   <div class="form-group row">
    <div class="col-sm-3">氏名</div>
     <div><%= @customer.last_name %><%= @customer.first_name %></div>
   </div>

   <div class="form-group row">
    <div class="col-sm-3">フリガナ</div>
     <div><%= @customer.last_name_kana %><%= @customer.first_name_kana %></div>
   </div>

   <div class="form-group row">
    <div class="col-sm-3">郵便番号</div>
     <div><%= @customer.postal_code %></div>
   </div>

   <div class="form-group row">
    <div class="col-sm-3">住所</div>
     <div><%= @customer.address %></div>
   </div>

 　<div class="form-group row">
    <div class="col-sm-3">電話番号</div>
     <div><%= @customer.telephone_number %></div>
 　</div>

 　<div class="form-group row">
    <div class="col-sm-3">メールアドレス</div>
     <div><%= @customer.email %></div>
   </div>

   <div class="form-group row">
    <div class="col-sm-3">会員ステータス</div>
     <div><% if @customer.is_active %>
      <span class="green">有効</span>
      <% else %>
      <span class="secondary">退会</span>
      <% end %>
     </div>
   </div>

  <div class="form-group row">
   <div class="col-sm-5 text-right"><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></div>
   <div class="col-sm-6"><%= link_to "注文履歴一覧をみる", orders_path, class:"btn btn-primary ml-3" %></div>
 </div>
</div>