config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'

devise_scope :customer do
  get '/customers/sign_up', to: 'customers/registrations#new'
  post '/customers', to: 'customers/registrations#create'

  get '/customers/sign_in', to: 'customers/sessions#new'
  post '/customers/sign_in', to: 'customers/sessions#create'
  delete '/customers/sign_out', to: 'customers/sessions#destroy'
end


devise_for :customers, skip: [:registrations, :sessions, :passwords]

devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

scope module: :public do

get 'home/about' => 'homes#about'

resources :items, only: [:index, :show]
#get '/items' => 'items#index'
#get '/items/:id' => 'items#show'

#get '/customers/edit' => 'customers#edit'
#patch '/customers' => 'customers#update'
#get '/customers' => 'customers#show'
get '/customers/unsubscribe' => 'customers#unsubscribe'
patch '/customers/withdraw' => 'customers#withdraw'
resource :customers, only: [:show, :edit, :update]

delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
resources :cart_items, except: [:show, :edit, :new]

get '/orders/confirm' => 'orders#confirm'
get '/orders/complete' => 'orders#complete'
resources :orders
#post '/orders' => 'orders#create'
#get '/orders' => 'orders#index'
#get '/orders/:id' => 'orders#show'
#get '/orders/new' => 'orders#new'

#get '/addresses' => 'addresses#index'
#get '/addresses/:id/edit' => 'addresses#edit'
#post '/addresses' =>'addresses#create'
#patch '/addresses/:id' => 'addresses#update'
#delete '/addresses/:id' => 'addresses#destroy'

resources :addresses

end




 namespace :admin do
  resources :customers
  resources :genres
  resources :items
  resources :orders
  resources :order_items
 end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def view_postal_code_and_address_and_name
    '〒' + self.postal_code + ' ' + self.address + ' ' + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

   has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image

  has_many :cart_items
  has_many :order_items
  belongs_to :genre
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: {銀行振込:0, クレジットカード:1}
  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}

  def sum
   sum = 0
   self.order_items.each do |order_item|
   sum += order_item.item.price * order_item.amount

   end
   return sum
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}



end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  	if @customer.update(customer_params)
  		redirect_to admin_customer_path(@customer)
  	else
  		render "edit"
  	end
  end

  private

  def customer_params
  	params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :postal_code,:address, :phone_number, :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 def index
    @genre = Genre.new
    @genres = Genre.all
 end

 def edit
   @genre = Genre.find(params[:id])
 end

 def create
    @genre = Genre.new(genre_params)
      if @genre.save
     flash[:success] = "aa "
     redirect_to admin_genres_path
      else
    @genres = Genre.all
     render :index
      end
 end


 def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
    flash[:success] = "aa"
    redirect_to admin_genres_path
    else
      render :index
    end
 end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

 def top
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def index
@items = Item.all
end

def new
  @item = Item.new
end

def create
  @item = Item.new(item_params)
   if @item.save
  redirect_to admin_item_path(@item)
   else
     render :new
   end
end

def show
  @item = Item.find(params[:id])
end

def edit
 @item = Item.find(params[:id])
end

def update
 @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to admin_items_path(@item)
  else
     render :edit
  end
end



private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def index
 @orders = Order.all
end

def show
 @order = Order.find(params[:id])
 @order_items = @order.order_items
end

def update
 @order = Order.find(params[:id])
 @order.update(order_params)
 @order_items = @order.order_items
 
 if @order.status == "入金確認"
  @order_items.each do |order_item|
   order_item.making_status = "製作待ち"
   order_item.save
  end
 end
 
 redirect_to admin_order_path(@order)
end

private
	def order_params
		params.require(:order).permit(:status)
	end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_out_path_for(resources)
    if resources == :admin
      #flash[:success] = "Signed out successfully."
      new_admin_session_path
    else
      customers_sign_in_path
    end
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>

<div class="row">
  <div class="col-md-11 offset-md-1">
    <%= form_with model:@genre, url: admin_genre_path(@genre), local:true do |f| %>
      <p class="d-inline-block">ジャンル名</p>
      <%= f.text_field :name, class: "ml-3" %>
    　<%= f.submit'変更を保存', class: "btn outline btn-success" %>
    <% end %>
  </div>
 </div>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2>

<div class="row">
  <div class="col-md-11 offset-md-1">
    <div class="row">
      <%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
        <p class="d-inline-block">ジャンル名</p>
        <%= f.text_field :name, class: "ml-3" %>
        <%= f.submit'新規登録', class: "btn outline btn-success ml-3" %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th></th>
              <th>ジャンル</th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to '編集する', edit_admin_genre_path(genre), class: "btn outline btn-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_with model:@item, url: admin_item_path(@item),method: :patch, local:true do |f| %>

<div class="row">
  <div class="offset-sm-3"></div>
  <div class="col-sm-6">

  <div class="form-group row">
    <%= f.label :image,"商品画像" , class:"col-sm-3 col-form-label" %>
    <div class="col-sm-">
      <%= f.attachment_field :image %>
    </div>
  </div>

   <div class="form-group row">
    <%= f.label :name,"商品名" , class:"col-sm-3 col-form-label" %>
    <div class="col-sm-5">
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>

   <div class="form-group row">
    <%= f.label :introduction,"商品説明" , class:"col-sm-3 col-form-label" %>
    <div class="col-sm-5">
      <%= f.text_field :introduction, class:"form-control" %>
    </div>
  </div>

    <div class="form-group row">
    <%= f.label :genre,"ジャンル" , class:"col-sm-3 col-form-label" %>
    <div class="col-sm-5">
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい", class:"form-control" %>
    </div>
  </div>

   <div class="form-group row">
    <%= f.label :price,"税抜き価格" , class:"col-sm-3 col-form-label" %>
    <div class="col-sm-5">
      <%= f.text_field :price, class:"form-control" %>
    </div>
  </div>

     <div class="form-group row">
    <%= f.label :is_active,"販売ステータス" , class:"col-sm-3 col-form-label" %>
    <div class="col-sm-5">
      <%= f.label :is_active, '販売中' %>
      <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active, '販売停止中' %>
      <%= f.radio_button :is_active, :false %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-7 offset-sm-4">
      <%= f.submit "変更を保存",class:"btn btn-success" %>
    </div>
  </div>

<% end %>

</div>

app/views/admin/items/index.html.erb
<div class="row">
  <div class="offset-md-2"></div>
  <div class="col-md-8">

    <h2>商品一覧</h2>

      <div class="text-right">
        <%= link_to '＋', new_admin_item_path, class: "btn btn-circle" %>
      </div>

    <table class="table">
     <thead class="thead-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
          <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name , admin_item_path(item) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active %>
              <span class="green">販売中</span>
            <% else %>
              <span class="secondary">販売停止中</span>
          <% end %>
          </td>
        </tr>

          <% end %>
      </tbody>
    </table>

　</div>
</div>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>
  <%= form_with model:@item, url: admin_items_path, local:true do |f| %>

  <div class="form-group row">
    <%= f.label :image,"商品画像" , class:"col-sm-2 col-form-label" %>
    <div class="col-sm-2">
      <%= f.attachment_field :image %>
    </div>
  </div>

   <div class="form-group row">
    <%= f.label :name,"商品名" , class:"col-sm-2 col-form-label" %>
    <div class="col-sm-2">
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :introduction,"商品説明" , class:"col-sm-2 col-form-label" %>
    <div class="col-sm-2">
      <%= f.text_field :introduction, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :genre_id,"ジャンル" , class:"col-sm-2 col-form-label" %>
    <div class="col-sm-2">
    <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :price,"税抜価格" , class:"col-sm-2 col-form-label" %>
    <div class="col-sm-2">
      <%= f.text_field :price, class:"form-control" %><p>円</p>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :is_active,"販売ステータス" , class:"col-sm-2 col-form-label" %>
    <div class="col-sm-2">
      <%= f.label :is_active, '販売中' %>
      <%= f.radio_button :is_active, :true %>
　　　<%= f.label :is_active, '販売停止中' %>
      <%= f.radio_button :is_active, :false %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= f.submit "新規登録",class:"btn btn-success" %>
    </div>
  </div>

<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>

<div class="row">
 <div class="col-md-4">
  <div class="text-right">
    <%= attachment_image_tag @item, :image, :fill, 200, 200, format: 'jpeg' %>
  </div>
 </div>

<div class="col-md-5">
  <div class="form-group row">
   <h4>商品名</h4>
   <div><%= @item.name %></div>
  </div>

  <div class="form-group row">
   <h4>商品説明</h4>
   <div><%= @item.introduction %></div>
  </div>

  <div class="form-group row">
   <h4>ジャンル</h4>
   <div><%= @item.genre.name %></div>
  </div>

  <div class="form-group row">
   <h4>税込価格（税抜価格）</h4>
   <div><%= @item.price %></div>円
  </div>

  <div class="form-group row">
   <h4>販売ステータス</h4>
   <div><% if @item.is_active %>
    販売中
     <% else %>
    販売停止中
     <% end %>
   </div>
  </div>

 <div><%= link_to "編集する" , edit_admin_item_path(@item) , class:"btn btn-success" %></div>
</div>
</div>

app/views/admin/orders/index.html.erb
<h2>注文履歴一覧</h2>

<dic class ="row col-sm-8 offset-sm-2">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.created_at, admin_order_path(order) %></td>
        <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
        <td><%= order.order_items.all.sum(:amount) %></td>
        <td><%= order.status %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>

<div class="col-sm-9">
  <div class="form-group row">
    <h4>購入者</h4>
     <div><%= @order.customer.last_name %><%= @order.customer.first_name %></div>
  </div>

  <div class="form-group row">
    <h4>注文日</h4>
    <div><%= @order.created_at %></div>
  </div>

  <div class="form-group row">
   <h4>配送先</h4>
   <div>〒<%= @order.postal_code %><%= @order.address %><br><%= @order.name %></div>
  </div>

  <div class="form-group row">
   <h4>支払方法</h4>
   <div><%= @order.payment_method %></div>
  </div>

  <div class="form-group row">
   <h4>注文ステータス</h4>
    <%= form_with model:@order, url: admin_order_path, local:true do |f| %>
          　<%= f.select :status,["入金待ち","入金確認","製作中","発送準備中","発送済"]  %>
          <%= f.submit "更新" ,class: "btn btn-success btn-sm" %></td>
    <% end %>
  </div>
  </div>

<div class=" col-xs-10">
   <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
    </thead>
    <tbody>
      <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.item.name %></td>
        <td><%= order_item.price %></td>
        <td><%= order_item.amount %></td>
        <td><%= order_item.price %></td>
        <td>
            <%= form_with model:order_item, url: admin_order_item_path(order_item), local:true, method: :patch do |f| %>
            <%= f.select :making_status,["着手不可","製作待ち","製作中","製作完了"] %>
             <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
        </td>
      </tr>
      <% end %>

    </tbody>
  </table>

   <div class="total">
       <h4>商品合計 <%= @order.total_payment %>円</h4>
       <h4>送料 <%= @order.shipping_cost %>円</h4>
       <h4>請求金額合計 <%= (@order.total_payment + @order.shipping_cost) %>円</h4>
   </div>
   </div>